variables:
  API_IMAGE: aviralworld/backend
  API_IMAGE_TAG: latest

stages:
  - test
  - docker

test:
  stage: test
  image: "shivjm/node-chromium-alpine:node14.15.3-chromium81.0.4044.113"
  services:
    - adobe/s3mock:2.1.24@sha256:f444c12e38050dcf339e8784cacfa40d14a4876503d2818982acb7f117ef03df
    - name: $CI_REGISTRY/$API_IMAGE/db:$API_IMAGE_TAG
      alias: db
    - $CI_REGISTRY/$API_IMAGE:$API_IMAGE_TAG
  variables:
    MOCHA_TIMEOUT: "60000"

    POSTGRES_PASSWORD: "1234"
    POSTGRES_DB: aviralworld
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_USER: postgres

    BACKEND_DB_CONNECTION_STRING: "postgresql://postgres@db:5432/aviralworld"
    BACKEND_S3_ACL: "public-read"
    BACKEND_S3_CACHE_CONTROL: "public, max-age=604800, immutable"
    BACKEND_BASE_URL: "https://www.example.com/"
    BACKEND_RECORDINGS_PATH: "recordings"
    BACKEND_PORT: "3030"
    BACKEND_ADMIN_PORT: "3031"
    BACKEND_TOKENS_PER_RECORDING: "2"

    FRONTEND_API_URL: "http://127.0.0.1:3030/"
    FRONTEND_DEBOUNCE_DELAY_MS: "300"
    FRONTEND_ENABLE_ADMIN_MODE: "1"
    FRONTEND_RANDOM_STORY_COUNT: "3"
    FRONTEND_SERVE_STATIC: "1"

    FRONTEND_TEST_NAVIGATION_TIMEOUT: "5000"

    S3_ACCESS_KEY: something
    S3_SECRET_ACCESS_KEY: something_else
    S3_REGION_NAME: fake
    S3_BUCKET_NAME: test
    S3_ENDPOINT: "http://adobe-s3mock/"
    S3_BASE_URL: "http://adobe-s3mock/"

    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "1"
    PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"

    # for the test script
    PG_CONNECTION_STRING: "postgresql://postgres@db:5432/aviralworld"

    ROARR_LOG: "true"
  before_script:
    - npm i -g pnpm
    - pnpm i -s --frozen-lockfile
  script:
    - pnpm run lint --silent
    - pnpm test
  only:
    - merge_requests
  interruptible: yes

docker:
  stage: docker
  variables:
    KANIKO_AUTH_CONFIG: >-
        {
          "auths": {
            "$CI_REGISTRY": {
              "username": "$CI_REGISTRY_USER",
              "password": "$CI_REGISTRY_PASSWORD"
            }
          }
        }
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $KANIKO_AUTH_CONFIG > /kaniko/.docker/config.json
    - export build_timestamp=`date +%Y%m%d%H%M%S`
    - export tag="v$build_timestamp"
    - echo $tag
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --cache=true --destination=$CI_REGISTRY_IMAGE:$tag --destination=$CI_REGISTRY_IMAGE:latest --build-arg REVISION=$CI_COMMIT_SHA --build-arg TIMESTAMP=$build_timestamp
  only:
    - master
