variables:
  API_IMAGE: aviralworld/backend
  API_IMAGE_TAG: latest

stages:
  - test
  - docker

test:
  stage: test
  image: node:14.7.0-slim@sha256:684feb573d3e0433f05e2ca9d71c46997f6f9a9610ccb46705a0385c46d8c427
  services:
    - $API_IMAGE:$API_IMAGE_TAG
    - postgres:12.3-alpine@sha256:4c5db602c06b811737746e4564040e554ba68cd2ded46a736cbe1af3a638ed0a
    - adobe/s3mock:2.1.24@sha256:f444c12e38050dcf339e8784cacfa40d14a4876503d2818982acb7f117ef03df
  before_script:
    - npm i -g pnpm
    - pnpm i --frozen-lockfile
  script:
    - pnpm run lint
    # TODO add test data
    - pnpm test
  only: []
  # TODO implement testing
  interruptible: yes

docker:
  stage: docker
  variables:
    KANIKO_AUTH_CONFIG: >-
        {
          "auths": {
            "$CI_REGISTRY": {
              "username": "$CI_REGISTRY_USER",
              "password": "$CI_REGISTRY_PASSWORD"
            }
          }
        }
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo $KANIKO_AUTH_CONFIG > /kaniko/.docker/config.json
    - export build_timestamp=`date +%Y%m%d%H%M%S`
    - export tag="v$build_timestamp"
    - echo $tag
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --cache=true --destination=$CI_REGISTRY_IMAGE:$tag --destination=$CI_REGISTRY_IMAGE:latest --build-arg FRONTEND_REVISION=$CI_COMMIT_SHA --build-arg TIMESTAMP=$build_timestamp
  only:
    - master
