ARG BASE_IMAGE
ARG NGINX_VERSION

FROM $BASE_IMAGE AS build

FROM nginxinc/nginx-unprivileged:$NGINX_VERSION

ARG TIMESTAMP
ARG REVISION

LABEL timestamp=$TIMESTAMP revision=$REVISION

COPY --from=build /app/static /usr/share/nginx/html/static
COPY --from=build /app/__sapper__/build/client /usr/share/nginx/html/client

COPY nginx/nginx.template.conf /etc/nginx/templates/default.conf.template
