ARG BASE_IMAGE
ARG NGINX_VERSION

FROM $BASE_IMAGE AS build

FROM nginx:$NGINX_VERSION

ARG TIMESTAMP
ARG REVISION

LABEL timestamp=$TIMESTAMP revision=$REVISION

COPY --from=build /app/static /usr/share/nginx/html/static

COPY nginx/nginx.template.conf /etc/nginx/templates/default.conf.template
