ARG NODE_VERSION

FROM node:$NODE_VERSION AS build

ARG REVISION
ARG TIMESTAMP

LABEL timestamp=$TIMESTAMP revision=$REVISION

WORKDIR /app

COPY . .

RUN npm i -g pnpm && pnpm i -s --frozen-lockfile && DOTENV_FILE=testing.env pnpm run build && pnpm run hash
